[package]
name = "sqlite-compress"
version = "0.1.0"
edition = "2021"
autobenches = false

[dependencies]
sqlite-loadable = {git = "https://github.com/caido/dependency-sqlite-loadable-rs",branch = "caido",default-features = false,features = ["dynamic"]}
zstd = { version = "0.13.3", features = ["zdict_builder"] }
thiserror = "2.0.19"
parking_lot = "0.12.5"
zerocopy = { version = "0.8.56", features = ["derive"] }
clap = { version = "4", features = ["derive"], optional = true }
rand = { version = "0.8", optional = true }
rusqlite = { version = "0.32", features = ["bundled", "load_extension"], optional = true }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
criterion = "0.5"
rand = "0.8"
rusqlite = { version = "0.32", features = ["bundled", "load_extension"] }

[features]
default = []

[lib]
crate-type=["cdylib","rlib"]

[[bench]]
name = "insert_basic"
harness = false

[[bench]]
name = "select_basic"
harness = false

[[bench]]
name = "compress_basic"
harness = false

[[bench]]
name = "decompress_basic"
harness = false
