[package]
name = "sqlite-compress"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-ffi = { path = "./crates/sqlite-ffi", default-features = false, features = ["loadable_extension"] }
zstd = { version = "0.13.3", features = ["zdict_builder"] }
parking_lot = "0.12.4"
zerocopy = { version = "0.8.56", features = ["derive"] }
thiserror = {workspace=true}
libsqlite3-sys = {workspace=true}

[lib]
crate-type=["cdylib","rlib"]

[workspace]
members = [".", "crates/sqlite-ffi", "crates/sqlite-ffi-demo"]
resolver = "2"

[workspace.dependencies]
thiserror = "2.0.20"
libsqlite3-sys = { git = "https://github.com/rusqlite/rusqlite", package = "libsqlite3-sys" }

[patch.crates-io]
libsqlite3-sys = { git = "https://github.com/rusqlite/rusqlite", package = "libsqlite3-sys" }