[tools]
"cargo:cargo-llvm-cov" = "latest"
"rust" = [
  { version = "1.95.0", profile = "minimal", components = "rustfmt,clippy,rust-analyzer" },
  { version = "nightly-2026-04-06", profile = "minimal", components = "rustfmt" },
]
