name: Validate

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_ENV: ci

jobs:
  fmt:
    name: Format
    runs-on: warp-ubuntu-latest-x64-2x
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Mise
        uses: caido/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }}
          install: true
          cache: false
          log_level: debug
          install_args: --env ${{ env.MISE_ENV }}
      - name: Check formatting
        run: mise run fmt:prod

  clippy:
    name: ${{ matrix.component }} / clippy
    runs-on: warp-ubuntu-latest-x64-2x
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        component: [sqlite-compress]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Mise
        uses: caido/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }}
          install: true
          cache: false
          log_level: debug
          install_args: --env ${{ env.MISE_ENV }}
      - name: Run clippy
        run: mise run ${{ matrix.component }}:clippy

  test:
    name: ${{ matrix.component }} / test
    runs-on: warp-ubuntu-latest-x64-2x
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        component: [sqlite-compress]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Mise
        uses: caido/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }}
          install: true
          cache: false
          log_level: debug
          install_args: --env ${{ env.MISE_ENV }}
      - name: Run tests
        run: mise run ${{ matrix.component }}:test
  miri:
    name: ${{ matrix.component }} / miri
    runs-on: warp-ubuntu-latest-x64-2x
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        component: [sqlite-ffi]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Mise
        uses: caido/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: ${{ vars.CI__MISE_VERSION }}
          install: true
          cache: false
          log_level: debug
          install_args: --env ${{ env.MISE_ENV }}
      - name: Run Miri
        run: mise run ${{ matrix.component }}:miri